"""Render the final karaoke video with ffmpeg.

Burns ASS subtitles over a plain background with the instrumental audio.
"""

from __future__ import annotations

import logging
import platform
from pathlib import Path

from bhajan.config import (
    DEFAULT_BG_COLOR,
    DEFAULT_VIDEO_FPS,
    DEFAULT_VIDEO_HEIGHT,
    DEFAULT_VIDEO_WIDTH,
    FFMPEG_BIN,
    FFPROBE_BIN,
)
from bhajan.logger import StageLogger
from bhajan import subprocess_utils

log = logging.getLogger("bhajan")
stage = StageLogger(log, "render")


def render_video(
    *,
    instrumental_path: Path,
    ass_path: Path,
    output_path: Path,
    width: int = DEFAULT_VIDEO_WIDTH,
    height: int = DEFAULT_VIDEO_HEIGHT,
    fps: int = DEFAULT_VIDEO_FPS,
    bg_color: str = DEFAULT_BG_COLOR,
) -> Path:
    """Create an MP4 video by combining:

    1. A solid-colour background (generated by ffmpeg)
    2. The instrumental audio track
    3. ASS subtitles burned into the video

    Parameters
    ----------
    instrumental_path : Path to the instrumental-only WAV/MP3.
    ass_path : Path to the karaoke .ass subtitle file.
    output_path : Where to write the final MP4.
    width, height, fps : Video dimensions / frame-rate.
    bg_color : Hex colour string (e.g. ``"0c0c1e"``).

    Returns
    -------
    Path to the rendered MP4.
    """
    stage.info("Rendering karaoke video (%dx%d @ %dfps) ...", width, height, fps)
    stage.info("  Audio: %s", instrumental_path)
    stage.info("  Subs:  %s", ass_path)

    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Determine audio duration so we know how long the background should be
    duration = _probe_duration(instrumental_path)
    stage.info("  Duration: %.1f s", duration)

    # ASS filter with style overrides for on-screen readability
    # Import config values for style overrides
    from bhajan.config import DEFAULT_FONT, DEFAULT_FONT_SIZE
    # Use a platform-safe path separator for the ass filename
    ass_path_str = str(ass_path).replace("\\", "/")
    # Force style overrides to ensure proper sizing and positioning
    subtitles_filter = (
        f"subtitles='{ass_path_str}':force_style='PlayResX={width},"
        f"PlayResY={height},FontSize={DEFAULT_FONT_SIZE},Alignment=5'"
    )

    cmd = [
        FFMPEG_BIN,
        "-y",
        # ---- input 1: solid-colour background (lavfi) ----
        "-f", "lavfi", "-i",
        f"color=c={bg_color}:s={width}x{height}:r={fps},format=yuv420p",
        # ---- input 2: instrumental audio ----
        "-i", str(instrumental_path),
        # ---- video filter chain: subtitles ----
        "-vf", subtitles_filter,
        # ---- trim to audio duration ----
        "-t", str(duration),
        # ---- encoding settings ----
        "-c:v", "libx264",
        "-preset", "medium",
        "-crf", "23",
        "-c:a", "aac",
        "-b:a", "192k",
        "-shortest",
        str(output_path),
    ]

    subprocess_utils.check_call(cmd, timeout=7200)
    size_mb = output_path.stat().st_size / 1_048_576
    stage.info("Final video saved -> %s  (%.1f MB)", output_path, size_mb)
    return output_path


def _probe_duration(audio_path: Path) -> float:
    """Use ffprobe to get the duration in seconds."""
    cmd = [
        FFPROBE_BIN,
        "-v", "error",
        "-show_entries", "format=duration",
        "-of", "default=noprint_wrappers=1:nokey=1",
        str(audio_path),
    ]
    result = subprocess_utils.check_call(cmd)
    try:
        return float(result.stdout.strip())
    except (ValueError, TypeError):
        stage.warning("Could not probe duration; defaulting to 300 s")
        return 300.0
